LIBS = -lallegro -lallegro_primitives -lallegro_font -lallegro_ttf -lallegro_image -lallegro_audio -lallegro_acodec
SRCS = $(wildcard *.c) $(wildcard **/*.c)

target1:
	$(CC) $(SRCS) $(LIBS) -o ship_v3
